# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import workloadQuery_pb2 as workloadQuery__pb2


class WorkloadQueryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSamples = channel.unary_unary(
        '/WorkloadQuery/GetSamples',
        request_serializer=workloadQuery__pb2.RequestForWorkload.SerializeToString,
        response_deserializer=workloadQuery__pb2.ResponseForData.FromString,
        )


class WorkloadQueryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSamples(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorkloadQueryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSamples': grpc.unary_unary_rpc_method_handler(
          servicer.GetSamples,
          request_deserializer=workloadQuery__pb2.RequestForWorkload.FromString,
          response_serializer=workloadQuery__pb2.ResponseForData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WorkloadQuery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
