# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workloadQuery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='workloadQuery.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13workloadQuery.proto\"\xdb\x01\n\x12RequestForWorkload\x12\r\n\x05rfwId\x18\x01 \x01(\x06\x12\x38\n\rbenchmarkType\x18\x02 \x01(\x0b\x32!.RequestForWorkload.BenchmarkType\x12\x16\n\x0eworkloadMetric\x18\x03 \x01(\t\x12\x11\n\tbatchUnit\x18\x04 \x01(\x05\x12\x0f\n\x07\x62\x61tchId\x18\x05 \x01(\x05\x12\x11\n\tbatchSize\x18\x06 \x01(\x05\x1a-\n\rBenchmarkType\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"N\n\x0fResponseForData\x12\r\n\x05rfwId\x18\x01 \x01(\x06\x12\x13\n\x0blastBatchId\x18\x02 \x01(\x05\x12\x17\n\x07\x62\x61tches\x18\x03 \x01(\x0b\x32\x06.Batch\"!\n\x05\x42\x61tch\x12\x18\n\x07samples\x18\x01 \x03(\x0b\x32\x07.Sample\"g\n\x06Sample\x12\x0e\n\x06\x63puAvg\x18\x01 \x01(\r\x12\x11\n\tnetworkIn\x18\x02 \x01(\r\x12\x12\n\nnetworkOut\x18\x03 \x01(\r\x12\x11\n\tmemoryAvg\x18\x04 \x01(\x01\x12\x13\n\x0b\x66inalTarget\x18\x05 \x01(\x01\x32\x46\n\rWorkloadQuery\x12\x35\n\nGetSamples\x12\x13.RequestForWorkload\x1a\x10.ResponseForData\"\x00\x62\x06proto3')
)




_REQUESTFORWORKLOAD_BENCHMARKTYPE = _descriptor.Descriptor(
  name='BenchmarkType',
  full_name='RequestForWorkload.BenchmarkType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='RequestForWorkload.BenchmarkType.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='RequestForWorkload.BenchmarkType.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=243,
)

_REQUESTFORWORKLOAD = _descriptor.Descriptor(
  name='RequestForWorkload',
  full_name='RequestForWorkload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfwId', full_name='RequestForWorkload.rfwId', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='benchmarkType', full_name='RequestForWorkload.benchmarkType', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workloadMetric', full_name='RequestForWorkload.workloadMetric', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchUnit', full_name='RequestForWorkload.batchUnit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchId', full_name='RequestForWorkload.batchId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='RequestForWorkload.batchSize', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUESTFORWORKLOAD_BENCHMARKTYPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=243,
)


_RESPONSEFORDATA = _descriptor.Descriptor(
  name='ResponseForData',
  full_name='ResponseForData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfwId', full_name='ResponseForData.rfwId', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastBatchId', full_name='ResponseForData.lastBatchId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batches', full_name='ResponseForData.batches', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=323,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='Batch.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=358,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuAvg', full_name='Sample.cpuAvg', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='networkIn', full_name='Sample.networkIn', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='networkOut', full_name='Sample.networkOut', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memoryAvg', full_name='Sample.memoryAvg', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalTarget', full_name='Sample.finalTarget', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=463,
)

_REQUESTFORWORKLOAD_BENCHMARKTYPE.containing_type = _REQUESTFORWORKLOAD
_REQUESTFORWORKLOAD.fields_by_name['benchmarkType'].message_type = _REQUESTFORWORKLOAD_BENCHMARKTYPE
_RESPONSEFORDATA.fields_by_name['batches'].message_type = _BATCH
_BATCH.fields_by_name['samples'].message_type = _SAMPLE
DESCRIPTOR.message_types_by_name['RequestForWorkload'] = _REQUESTFORWORKLOAD
DESCRIPTOR.message_types_by_name['ResponseForData'] = _RESPONSEFORDATA
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestForWorkload = _reflection.GeneratedProtocolMessageType('RequestForWorkload', (_message.Message,), {

  'BenchmarkType' : _reflection.GeneratedProtocolMessageType('BenchmarkType', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTFORWORKLOAD_BENCHMARKTYPE,
    '__module__' : 'workloadQuery_pb2'
    # @@protoc_insertion_point(class_scope:RequestForWorkload.BenchmarkType)
    })
  ,
  'DESCRIPTOR' : _REQUESTFORWORKLOAD,
  '__module__' : 'workloadQuery_pb2'
  # @@protoc_insertion_point(class_scope:RequestForWorkload)
  })
_sym_db.RegisterMessage(RequestForWorkload)
_sym_db.RegisterMessage(RequestForWorkload.BenchmarkType)

ResponseForData = _reflection.GeneratedProtocolMessageType('ResponseForData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEFORDATA,
  '__module__' : 'workloadQuery_pb2'
  # @@protoc_insertion_point(class_scope:ResponseForData)
  })
_sym_db.RegisterMessage(ResponseForData)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'workloadQuery_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  })
_sym_db.RegisterMessage(Batch)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'workloadQuery_pb2'
  # @@protoc_insertion_point(class_scope:Sample)
  })
_sym_db.RegisterMessage(Sample)



_WORKLOADQUERY = _descriptor.ServiceDescriptor(
  name='WorkloadQuery',
  full_name='WorkloadQuery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=465,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSamples',
    full_name='WorkloadQuery.GetSamples',
    index=0,
    containing_service=None,
    input_type=_REQUESTFORWORKLOAD,
    output_type=_RESPONSEFORDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKLOADQUERY)

DESCRIPTOR.services_by_name['WorkloadQuery'] = _WORKLOADQUERY

# @@protoc_insertion_point(module_scope)
