apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-workload
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    # targetPort: 8090
    # protocol: TCP
    # name: http2
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: esp-grpc-workload
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-workload
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-workload
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8080",
          # "--http2_port=8090",
          "--service=dataset.mohammadrafee.com",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8000"
        ]
        ports:
          - containerPort: 8080
      - name: workload
        image: gcr.io/assignemnt1-cloud-deployment/grpc-workload-server:latest
        ports:
          - containerPort: 8000
